# Please don't mess with the window values, though in theory everything should be fine
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 800

# The rest you can mess with
OFFSCREEN_WIGGLE = 50

PLAYER_SPEED = 250
ENEMY_SPEED = 90
SCROLL_SPEED = 75
BULLET_SPEED = 350

BULLET_TIME_TO_LIVE = 5

PLAYER_LEFT = (-PLAYER_SPEED, 0)
PLAYER_RIGHT = (PLAYER_SPEED, 0)
PLAYER_UP = (0, PLAYER_SPEED)
PLAYER_DOWN = (0, -PLAYER_SPEED)

BULLET_LEFT = (-BULLET_SPEED, 0)
BULLET_RIGHT = (BULLET_SPEED, 0)
BULLET_UP = (0, BULLET_SPEED)
BULLET_DOWN = (0, -BULLET_SPEED)

OBSTACLE_WALL = "w"
OBSTACLE_ENEMY = "e"

ENEMY_VERTICES = ((-15, -15), (15, -15), (-15, 15), (15, 15))
PLAYER_VERTICES = ((-12, 0), (12, 0), (0, 25))

COLOR_PLAYER = (0.9, 0.9, 0.9)
COLOR_WALL = (1.0, 0.0, 0.0)
COLOR_ENEMY = (0.9, 0.0, 0.9)
COLOR_BULLET = (0.0, 0.0, 1.0)

ENEMY_CHANCE_TO_FIRE = 0.95
